# Generated by Django 3.2.7 on 2021-12-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truck',
            options={'verbose_name': 'Foodtruck'},
        ),
        migrations.AlterModelOptions(
            name='truckimage',
            options={'verbose_name': 'Foodtruck Image'},
        ),
    ]
