# Generated by Django 3.2.7 on 2021-10-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='like',
                    name='product',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='product.product'),
                ),
            ],
            database_operations=[],
        ),
    ]
