# Generated by Django 3.2.7 on 2021-12-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_like_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Social'},
        ),
    ]
